from django.utils.translation import gettext_lazy as _

# GENRES

_("Action")
_("Adventure")
_("Avant Garde")
_("Award Winning")
_("Boys Love")
_("Comedy")
_("Drama")
_("Fantasy")
_("Girls Love")
_("Gourmet")
_("Horror")
_("Mystery")
_("Romance")
_("Sci-Fi")
_("Slice of Life")
_("Sports")
_("Supernatural")
_("Suspense")

# THEMES

_("Adult Cast")
_("Anthropomorphic")
_("CGDCT")
_("Childcare")
_("Combat Sports")
_("Crossdressing")
_("Delinquents")
_("Detective")
_("Educational")
_("Gag Humor")
_("Gore")
_("Harem")
_("High Stakes Game")
_("Historical")
_("Idols (Female)")
_("Idols (Male)")
_("Isekai")
_("Iyashikei")
_("Love Polygon")
_("Magical Sex Shift")
_("Mahou Shoujo")
_("Martial Arts")
_("Mecha")
_("Medical")
_("Military")
_("Music")
_("Mythology")
_("Organized Crime")
_("Otaku Culture")
_("Parody")
_("Performing Arts")
_("Pets")
_("Psychological")
_("Racing")
_("Reincarnation")
_("Reverse Harem")
_("Love Status Quo")
_("Samurai")
_("School")
_("Showbiz")
_("Space")
_("Strategy Game")
_("Super Power")
_("Survival")
_("Team Sports")
_("Time Travel")
_("Vampire")
_("Video Game")
_("Visual Arts")
_("Workplace")
_("Urban Fantasy")
_("Villainess")
_("Memoir")
_("Ecchi")
_("Erotica")
_("Hentai")
