# Generated by Django 6.0.5 on 2026-07-31 00:39

import django.core.validators
import django.db.models.deletion
import tracking.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField()),
                ('small_image_url', models.CharField(blank=True)),
                ('image_url', models.CharField(blank=True)),
                ('large_image_url', models.CharField(blank=True)),
                ('format', models.CharField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('synopsis', models.CharField(blank=True)),
                ('number_sections', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Finished', 'Terminé'), ('Publishing', 'En cours de publication'), ('On Hiatus', 'En pause'), ('Discontinued', 'Arrêté'), ('Not yet published', 'Pas encore sorti'), ('Finished Airing', 'Diffusion terminée'), ('Currently Airing', 'En cours de diffusion'), ('Not yet aired', 'Pas encore diffusé')])),
                ('user_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('user_completion', models.CharField(choices=[('Not Started', 'Non commencé'), ('In Progress', 'En cours'), ('Completed', 'Terminé')], default=tracking.enums.MediaCompletion['NOT_STARTED'])),
                ('user_current_section', models.IntegerField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mal_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DemographicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('mal_id_anime', models.IntegerField(null=True)),
                ('mal_id_manga', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('mal_id_anime', models.IntegerField(null=True)),
                ('mal_id_manga', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mal_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('mal_id_anime', models.IntegerField(null=True)),
                ('mal_id_manga', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('mediamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.mediamodel')),
                ('duration', models.CharField(blank=True)),
                ('rating', models.CharField(blank=True, choices=[('G - All Ages', 'Tout âge'), ('PG - Children', 'Jeune public'), ('PG-13 - Teens 13 or older', '13+'), ('R - 17+ (violence & profanity)', '17+ (violence et langage grossier)'), ('R+ - Mild Nudity', 'Nudité'), ('Rx - Hentai', 'Hentai')])),
                ('studios', models.ManyToManyField(to='tracking.studiomodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.mediamodel',),
        ),
        migrations.CreateModel(
            name='MangaModel',
            fields=[
                ('mediamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.mediamodel')),
                ('chapters', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='tracking.authormodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.mediamodel',),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='demographics',
            field=models.ManyToManyField(to='tracking.demographicmodel'),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='genres',
            field=models.ManyToManyField(to='tracking.genremodel'),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='themes',
            field=models.ManyToManyField(to='tracking.thememodel'),
        ),
        migrations.CreateModel(
            name='WatchlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('medias', models.ManyToManyField(to='tracking.mediamodel')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('filler', models.BooleanField(default=False)),
                ('recap', models.BooleanField(default=False)),
                ('user_score', models.IntegerField(blank=True, null=True)),
                ('user_completion', models.CharField(choices=[('not_started', 'Non commencé'), ('completed', 'Terminé')], default='not_started')),
                ('synopsis', models.CharField(blank=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tracking.animemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField(blank=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('user_score', models.IntegerField(blank=True, null=True)),
                ('user_completion', models.CharField(choices=[('not_started', 'Non commencé'), ('completed', 'Terminé')], default='not_started')),
                ('synopsis', models.CharField(blank=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='tracking.mangamodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediamodel',
            constraint=models.CheckConstraint(condition=models.Q(('user_score__gte', 0), ('user_score__lte', 10)), name='user_score_between_0_and_10'),
        ),
    ]
