# Generated by Django 6.0.5 on 2026-07-01 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField()),
                ('user_score', models.IntegerField(blank=True, null=True)),
                ('user_completion', models.CharField(choices=[('Finished', 'Finished'), ('Ongoing', 'Ongoing'), ('Unseen', 'Unseen')], default='Unseen')),
                ('user_current_section', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('synopsis', models.CharField(blank=True)),
                ('number_sections', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField()),
                ('status', models.CharField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mal_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DemographicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('mal_id_anime', models.IntegerField(null=True)),
                ('mal_id_manga', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('mal_id_anime', models.IntegerField(null=True)),
                ('mal_id_manga', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mal_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('mal_id_anime', models.IntegerField(null=True)),
                ('mal_id_manga', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('mediamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.mediamodel')),
                ('rating', models.CharField()),
                ('number_episodes', models.IntegerField(blank=True, null=True)),
                ('number_seasons', models.IntegerField(blank=True, null=True)),
                ('studios', models.ManyToManyField(to='tracking.studiomodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.mediamodel',),
        ),
        migrations.CreateModel(
            name='MangaModel',
            fields=[
                ('mediamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.mediamodel')),
                ('number_volumes', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='tracking.authormodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.mediamodel',),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='demographics',
            field=models.ManyToManyField(to='tracking.demographicmodel'),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='genres',
            field=models.ManyToManyField(to='tracking.genremodel'),
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_image_url', models.CharField()),
                ('medium_image_url', models.CharField()),
                ('large_image_url', models.CharField()),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracking.mediamodel')),
            ],
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='themes',
            field=models.ManyToManyField(to='tracking.thememodel'),
        ),
        migrations.CreateModel(
            name='WatchlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('medias', models.ManyToManyField(to='tracking.mediamodel')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField()),
                ('score', models.FloatField()),
                ('filler', models.BooleanField()),
                ('recap', models.BooleanField()),
                ('user_score', models.IntegerField()),
                ('user_completion', models.CharField(choices=[('Finished', 'Finished'), ('Unseen', 'Unseen')], default='Unseen')),
                ('synopsis', models.CharField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tracking.animemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField()),
                ('number', models.IntegerField()),
                ('score', models.FloatField()),
                ('user_score', models.IntegerField()),
                ('user_completion', models.CharField(choices=[('Finished', 'Finished'), ('Unseen', 'Unseen')], default='Unseen')),
                ('synopsis', models.CharField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='tracking.mangamodel')),
            ],
        ),
    ]
