# Generated by Django 6.0.5 on 2026-08-19 19:35

import tracking.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='synopsis_translated',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='title_english',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='title_french',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='rating',
            field=models.CharField(blank=True, choices=[('G - All Ages', 'All ages'), ('PG - Children', 'Young audience'), ('PG-13 - Teens 13 or older', '13+'), ('R - 17+ (violence & profanity)', 'Violence and profanity'), ('R+ - Mild Nudity', 'Mild nudity'), ('Rx - Hentai', 'Hentai')]),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Finished', 'Finished'), ('Publishing', 'Currently publishing'), ('On Hiatus', 'On hiatus'), ('Discontinued', 'Discontinued'), ('Not yet published', 'Not yet published'), ('Finished Airing', 'Finished airing'), ('Currently Airing', 'Currently airing'), ('Not yet aired', 'Not yet aired')]),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='user_completion',
            field=models.CharField(choices=[('Not Started', 'Not started'), ('In Progress', 'In progress'), ('Completed', 'Completed')], default=tracking.enums.MediaCompletion['NOT_STARTED']),
        ),
    ]
