# Generated by Django 6.0.5 on 2026-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='format',
            field=models.CharField(blank=True),
        ),
    ]
