# Generated by Django 6.0.5 on 2026-07-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='large_image_url',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='medium_image_url',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='small_image_url',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='rating',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='filler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='recap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='synopsis',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='user_completion',
            field=models.CharField(choices=[('not_started', 'Non commencé'), ('completed', 'Terminé')], default='not_started'),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='user_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='status',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='user_completion',
            field=models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='not_started'),
        ),
        migrations.AlterField(
            model_name='volumemodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volumemodel',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volumemodel',
            name='synopsis',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='volumemodel',
            name='title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='volumemodel',
            name='user_completion',
            field=models.CharField(choices=[('not_started', 'Non commencé'), ('completed', 'Terminé')], default='not_started'),
        ),
        migrations.AlterField(
            model_name='volumemodel',
            name='user_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ImagesModel',
        ),
    ]
