# Generated by Django 6.0.5 on 2026-07-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_mediamodel_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Finished', 'Terminé'), ('Publishing', 'En cours de publication'), ('On Hiatus', 'En pause'), ('Discontinued', 'Arrêté'), ('Not yet published', 'Pas encore sorti'), ('Finished Airing', 'Diffusion terminée'), ('Currently Airing', 'En cours de diffusion'), ('Not yet aired', 'Pas encore diffusé')]),
        ),
    ]
