# Generated by Django 6.0.5 on 2026-07-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tracking', '0002_alter_mediamodel_user_score'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mediamodel',
            constraint=models.CheckConstraint(condition=models.Q(('user_score__gte', 0), ('user_score__lte', 10)), name='user_score_between_0_and_10'),
        ),
    ]
